Fixed NPE during reporting (#318)
* Fixed potential NullPointerException.

There is evidence that the key sets of the sourceProxies and reporters
maps get inconsistent. I observe randomly failing builds that report the
following error:

```
FATAL: Cannot invoke "java.util.List.iterator()" because the return
value of "java.util.Map.get(Object)" is null
java.lang.NullPointerException: Cannot invoke
"java.util.List.iterator()" because the return value of
"java.util.Map.get(Object)" is null
	at hudson.maven.AbstractMavenBuilder.end(AbstractMavenBuilder.java:101)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:883)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:526)
	at hudson.model.Run.execute(Run.java:1895)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)
```

* Fixed indentation.