Fix test hudson.maven.Maven31xBuildTest#testSiteBuildWithForkedMojo on Mac OSX by upgrading the maven-javadoc-plugin version 2.7 -> 2.10.3 in the sample maven3-project.zip
Due to https://issues.apache.org/jira/browse/MJAVADOC-394 (fixed in maven-javadoc-plugin 2.10) the test hudson.maven.Maven31xBuildTest#testSiteBuildWithForkedMojo is failing because javadoc is not found by default under Oracle's JDK 7+ on Mac OSX:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project my-app-root: Error during page generation: Error rendering Maven report: Unable to find javadoc command: The javadoc executable '/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre/bin/javadoc' doesn't exist or is not a file. Verify the JAVA_HOME environment variable. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project my-app-root: Error during page generation