Fix test AbstractMaven3xBuildTest.testTychoEclipseTestResults
They are failing on my local environment with

```
Legacy code started this job.  No cause information is available
Building in workspace /var/folders/y_/wtlmkn492ldgqmswxk9tvwv00000gn/T/hudson1207747598863759080test/workspace/p
Deleting existing workspace /var/folders/y_/wtlmkn492ldgqmswxk9tvwv00000gn/T/hudson1207747598863759080test/workspace/p
Staging file:/Users/arnaud/Code/jenkinsci/maven-plugin/target/test-classes/hudson/maven/foobar_eclipse_with_fix.zip
Parsing POMs
Discovered a new module org.foobar:parent Foobar Build
Discovered a new module org.foobar:org.foobar Foobar
Discovered a new module org.foobar:org.foobar.test Foobar Test Suite
Modules changed, recalculating dependency graph
Established TCP socket on 55604
[org.foobar.build] $ /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre/bin/java -Djava.awt.headless=true -cp /Users/arnaud/.m2/repository/org/jenkins-ci/main/maven/maven31-agent/1.8-SNAPSHOT/maven31-agent-1.8-SNAPSHOT.jar:/Users/arnaud/Code/jenkinsci/maven-plugin/target/apache-maven-3.1.0/boot/plexus-classworlds-2.4.2.jar:/Users/arnaud/Code/jenkinsci/maven-plugin/target/apache-maven-3.1.0/conf/logging jenkins.maven3.agent.Maven31Main /Users/arnaud/Code/jenkinsci/maven-plugin/target/apache-maven-3.1.0 /Users/arnaud/.m2/repository/org/jenkins-ci/main/remoting/2.47/remoting-2.47.jar /Users/arnaud/.m2/repository/org/jenkins-ci/main/maven/maven31-interceptor/1.8-SNAPSHOT/maven31-interceptor-1.8-SNAPSHOT.jar /Users/arnaud/.m2/repository/org/jenkins-ci/main/maven/maven3-interceptor-commons/1.8-SNAPSHOT/maven3-interceptor-commons-1.8-SNAPSHOT.jar 55604
<===[JENKINS REMOTING CAPACITY]===>channel started
Executing Maven:  -B -f /var/folders/y_/wtlmkn492ldgqmswxk9tvwv00000gn/T/hudson1207747598863759080test/workspace/p/org.foobar.build/pom.xml verify
[INFO] Scanning for projects...
ha:AAAAYx+LCAAAAAAAAP9b85aBtbiIQSWjNKU4P0+vJLE4u1gvPjexLDVPzxdEhicW5WXmpfvll6S2fNly5fzGzauYGBgqihikoFqS8/OK83NS9ZwhNEghAwQwghQWAACwxA+XYgAAAA==[WARNING] No explicit target runtime environment configuration. Build is platform dependent.
ha:AAAAYx+LCAAAAAAAAP9b85aBtbiIQSWjNKU4P0+vJLE4u1gvPjexLDVPzxdEhicW5WXmpfvll6S2fNly5fzGzauYGBgqihikoFqS8/OK83NS9ZwhNEghAwQwghQWAACwxA+XYgAAAA==[WARNING] No explicit target runtime environment configuration. Build is platform dependent.
[INFO] Resolving target platform for project MavenProject: org.foobar:org.foobar:1.0.0 @ /var/folders/y_/wtlmkn492ldgqmswxk9tvwv00000gn/T/hudson1207747598863759080test/workspace/p/org.foobar/pom.xml
[INFO] Fetching p2.index (0B of 96B at 0B/s) from http://download.eclipse.org/releases/helios/p2.index
[INFO] Fetching p2.index (128B of 96B at 0B/s) from http://download.eclipse.org/releases/helios/p2.index
[INFO] 1 operation remaining.
[INFO] Adding repository http://download.eclipse.org/releases/helios
[INFO] Fetching p2.index (0B of 96B at 0B/s) from http://download.eclipse.org/releases/helios/p2.index
[INFO] 1 operation remaining.
[INFO] Fetching p2.index (128B of 96B at 0B/s) from http://download.eclipse.org/releases/helios/p2.index
[INFO] Adding repository http://download.eclipse.org/releases/helios
ha:AAAAYx+LCAAAAAAAAP9b85aBtbiIQSWjNKU4P0+vJLE4u1gvPjexLDVPzxdEhicW5WXmpfvll6S2fNly5fzGzauYGBgqihikoFqS8/OK83NS9ZwhNEghAwQwghQWAACwxA+XYgAAAA==[WARNING] org.foobar_1.0.0 has been replaced by another bundle with the same symbolic name org.foobar_1.0.0
ha:AAAAYB+LCAAAAAAAAP9b85aBtbiIQSmjNKU4P0+vJLE4u1gvPjexLDVPzxdEuhYV5Rf55ZekOlc7RKnPKH7IxMBQUcQgBdWQnJ9XnJ+TqucMoUEKGSCAEaSwAACsNFCqYAAAAA==[ERROR] Internal error: java.lang.NullPointerException -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.NullPointerException
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:165)
	at org.jvnet.hudson.maven3.launcher.Maven31Launcher.main(Maven31Launcher.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:331)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:239)
	at jenkins.maven3.agent.Maven31Main.launch(Maven31Main.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:136)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:71)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:324)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.eclipse.tycho.core.osgitools.EquinoxResolver.assertResolved(EquinoxResolver.java:222)
	at org.eclipse.tycho.core.osgitools.EquinoxResolver.newResolvedState(EquinoxResolver.java:65)
	at org.eclipse.tycho.core.osgitools.OsgiBundleProject.getResolverState(OsgiBundleProject.java:204)
	at org.eclipse.tycho.core.osgitools.OsgiBundleProject.resolve(OsgiBundleProject.java:150)
	at org.eclipse.tycho.core.resolver.DefaultTychoDependencyResolver.resolveProject(DefaultTychoDependencyResolver.java:101)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:91)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:272)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:153)
	... 22 more
ha:AAAAYB+LCAAAAAAAAP9b85aBtbiIQSmjNKU4P0+vJLE4u1gvPjexLDVPzxdEuhYV5Rf55ZekOlc7RKnPKH7IxMBQUcQgBdWQnJ9XnJ+TqucMoUEKGSCAEaSwAACsNFCqYAAAAA==[ERROR]
ha:AAAAYB+LCAAAAAAAAP9b85aBtbiIQSmjNKU4P0+vJLE4u1gvPjexLDVPzxdEuhYV5Rf55ZekOlc7RKnPKH7IxMBQUcQgBdWQnJ9XnJ+TqucMoUEKGSCAEaSwAACsNFCqYAAAAA==[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
ha:AAAAYB+LCAAAAAAAAP9b85aBtbiIQSmjNKU4P0+vJLE4u1gvPjexLDVPzxdEuhYV5Rf55ZekOlc7RKnPKH7IxMBQUcQgBdWQnJ9XnJ+TqucMoUEKGSCAEaSwAACsNFCqYAAAAA==[ERROR] Re-run Maven using the -X switch to enable full debug logging.
ha:AAAAYB+LCAAAAAAAAP9b85aBtbiIQSmjNKU4P0+vJLE4u1gvPjexLDVPzxdEuhYV5Rf55ZekOlc7RKnPKH7IxMBQUcQgBdWQnJ9XnJ+TqucMoUEKGSCAEaSwAACsNFCqYAAAAA==[ERROR]
ha:AAAAYB+LCAAAAAAAAP9b85aBtbiIQSmjNKU4P0+vJLE4u1gvPjexLDVPzxdEuhYV5Rf55ZekOlc7RKnPKH7IxMBQUcQgBdWQnJ9XnJ+TqucMoUEKGSCAEaSwAACsNFCqYAAAAA==[ERROR] For more information about the errors and possible solutions, please read the following articles:
ha:AAAAYB+LCAAAAAAAAP9b85aBtbiIQSmjNKU4P0+vJLE4u1gvPjexLDVPzxdEuhYV5Rf55ZekOlc7RKnPKH7IxMBQUcQgBdWQnJ9XnJ+TqucMoUEKGSCAEaSwAACsNFCqYAAAAA==[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
channel stopped
Finished: FAILURE

------
 expected:<SUCCESS> but was:<FAILURE>
```

Which comes from : https://bugs.eclipse.org/bugs/show_bug.cgi?id=340852

It is solved by upgrading tycho from 0.12.0 ->  0.13.0 in testcase foobar_eclipse_with_fix.zip